### ISSUE TITLE
422 error

### ISSUE THREAD

**Issue by nicolocarpignoli** [chialab/a11ygator-app#16]
API are giving a strange 422 error. Steps to reproduce:

* ask to check https://www.gazzetta.it

It will take some time. Then:

* ask to check https://www.repubblica.it/

It will fail from now on with the 422 code error.

**Comment by fquffio** [comment]
**422 Unprocessable Entity** is the HTTP status code returned when the report could not be generated due to some error with Pa11y: https://github.com/chialab/a11ygator-app/blob/master/lambda/report-view/index.js#L103

The problem is with Pa11y timing out.
