### ISSUE TITLE
Add cache control headers

### ISSUE THREAD

**Issue by fquffio** [chialab/a11ygator-app#4]
Since our deployment uses CloudFront to add CDN to the Express app, it's necessary to add caching information to prevent CloudFront caching contents that are not to be cached, like errors, and requests to `/reports` and `/screenshots/*` when storage adapter uses Google Cloud Storage.

**Comment by nicolocarpignoli** [comment]
fixed in https://github.com/chialab/a11ygator-app/pull/5
